server:
  port: 9090

dubbo:
  application:
    name: provider-demo
  protocol:
    name: dubbo
    port: 20885
  registry:
    id: my-registry
    protocol: zookeeper
    address: 127.0.0.1:2181

spring:
  application:
    name: provider-demo

#  datasource:
#    dynamic:
#      datasource:
#        master:
#          username: root
#          password: zhuang1220
#          url: jdbc:mysql://127.0.0.1:3306/guns?useSSL=false
#          driver-class-name: com.mysql.jdbc.Driver
#        slave_1:
#          username: root
#          password: zhuang1220
#          url: jdbc:mysql://127.0.0.1:3306/guns?useSSL=false
#          driver-class-name: com.mysql.jdbc.Driver
#        slave_2:
#          username: root
#          password: zhuang1220
#          url: jdbc:mysql://127.0.0.1:3306/guns2?useSSL=false
#          driver-class-name: com.mysql.jdbc.Driver

  datasource:
    dynamic:
      druid: #以下是全局默认值，可以全局更改
        initial-size: 0
        max-active: 8
        min-idle: 2
        max-wait: -1
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 0
        validation-query: select 1
        validation-query-timeout: -1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        max-open-prepared-statements: 100
        filters: stat,wall
        share-prepared-statements: true
      datasource:
        master:
          username: root
          password: zhuang1220
          url: jdbc:mysql://127.0.0.1:3306/guns?useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
          druid: #这里可以重写默认值
            initial-size: 5
        slave_1:
          username: root
          password: zhuang1220
          url: jdbc:mysql://127.0.0.1:3306/guns?useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
          druid:
            initial-size: 6
        slave_2:
          username: root
          password: zhuang1220
          url: jdbc:mysql://127.0.0.1:3306/guns2?useSSL=false
          driver-class-name: com.mysql.jdbc.Driver


logging:
    level:
      com.baomidou: debug